//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeszczeros
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Cst_ID { get; set; }
        public string Cst_Name { get; set; }
        public string Cst_TaxID { get; set; }
        public string Cst_StreetName { get; set; }
        public Nullable<int> Cst_StreetNumber { get; set; }
        public System.DateTime Cst_InsertDate { get; set; }
        public int Cst_InsertedBy { get; set; }
    }
}
