//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeszczeros
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessState
    {
        public int PSS_ID { get; set; }
        public string PSS_Name { get; set; }
        public System.DateTime PSS_InsertDate { get; set; }
        public int PSS_InsertedBy { get; set; }
    }
}
