//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeszczeros
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Usr_ID { get; set; }
        public string Usr_Name { get; set; }
        public string Usr_Surname { get; set; }
        public string Usr_Login { get; set; }
        public string Usr_PWD { get; set; }
        public string Usr_Email { get; set; }
        public System.DateTime Usr_InsertDate { get; set; }
        public int Usr_InsertedBy { get; set; }
    }
}
