//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralnyWPF_Workflow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int Doc_ID { get; set; }
        public string Doc_Name { get; set; }
        public Nullable<int> Doc_CstID { get; set; }
        public System.DateTime Doc_DocumentDate { get; set; }
        public Nullable<System.DateTime> Doc_SellDate { get; set; }
        public Nullable<System.DateTime> Doc_PaymentDate { get; set; }
        public int Doc_InsertedBy { get; set; }
        public System.DateTime Doc_InsertDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
