//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralnyWPF_Workflow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Tsk_ID { get; set; }
        public int Tsk_DocID { get; set; }
        public int Tsk_UsrID { get; set; }
        public System.DateTime Tsk_InsertDate { get; set; }
        public System.DateTime Tsk_UpdateDate { get; set; }
        public int Tsk_InsertedBy { get; set; }
        public int Tsk_Updatedby { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
    }
}
