//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralnyWPF_Workflow
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int Usr_ID { get; set; }
        public string Usr_Name { get; set; }
        public string Usr_Surname { get; set; }
        public string Usr_Login { get; set; }
        public string Usr_PWD { get; set; }
        public string Usr_Email { get; set; }
        public System.DateTime Usr_InsertDate { get; set; }
        public int Usr_InsertedBy { get; set; }
        public bool Usr_isAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
